from .configs import (
    STUBS_DEFAULT_PATH,
    PLAYER_DETECTOR_PATH,
    BALL_DETECTOR_PATH,
    COURT_KEYPOINT_DETECTOR_PATH,
    POSE_DETECTOR_PATH,
    POSE_3D_LIFTER_PATH,
    OUTPUT_VIDEO_PATH,
    YOLO_2D_OUTPUT_DIR,
    POSE_3D_OUTPUT_DIR,
)
